"""new 1.

Revision ID: 086b88300762
Revises: 
Create Date: 2024-04-11 02:18:21.636079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086b88300762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.Column('id_jobseeker', sa.Integer(), nullable=False),
    sa.Column('apply_job', sa.Enum('apply_status', name='apply_status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('detail_company', sa.Text(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobseeker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('exprience', sa.String(length=255), nullable=True),
    sa.Column('name_company', sa.String(length=255), nullable=True),
    sa.Column('field_work', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_company', sa.Integer(), nullable=True),
    sa.Column('name_job', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('exprience', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_company'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_job',
    sa.Column('id_job', sa.Integer(), nullable=False),
    sa.Column('id_company', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['id_job'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id_job', 'id_company')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_job')
    op.drop_table('job')
    op.drop_table('jobseeker')
    op.drop_table('company')
    op.drop_table('user')
    op.drop_table('timeline')
    # ### end Alembic commands ###
