"""new 1.

Revision ID: 45d2e5e92087
Revises: 086b88300762
Create Date: 2024-04-11 10:21:52.344065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d2e5e92087'
down_revision = '086b88300762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_user'])

    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id_user'])

    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'job', ['id_job'], ['id'])
        batch_op.create_foreign_key(None, 'jobseeker', ['id_jobseeker'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
