"""new 11.

Revision ID: 9aa898f973ab
Revises: 616d50419ad3
Create Date: 2024-04-15 22:32:13.088489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa898f973ab'
down_revision = '616d50419ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply_job', sa.Enum('pending', 'approved', 'rejected', name='apply_job_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.drop_column('apply_job')

    # ### end Alembic commands ###
