"""new 4.

Revision ID: e70144c786b2
Revises: 6007051a06e4
Create Date: 2024-04-14 21:04:50.894139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70144c786b2'
down_revision = '6007051a06e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.drop_column('exprience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exprience', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
