"""new 12.

Revision ID: fd83e3341d26
Revises: 9aa898f973ab
Create Date: 2024-04-17 12:05:44.511898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd83e3341d26'
down_revision = '9aa898f973ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_job',
    sa.Column('id_job', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_company', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_company'], ['company.id'], name='company_job_id_company_fkey'),
    sa.ForeignKeyConstraint(['id_job'], ['job.id'], name='company_job_id_job_fkey'),
    sa.PrimaryKeyConstraint('id_job', 'id_company', name='company_job_pkey')
    )
    # ### end Alembic commands ###
