"""new 5.

Revision ID: 709bc244a17b
Revises: e70144c786b2
Create Date: 2024-04-14 21:05:45.691104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709bc244a17b'
down_revision = 'e70144c786b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exprience', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.drop_column('exprience')

    # ### end Alembic commands ###
