"""new 8.

Revision ID: 8243964afff2
Revises: 937d05f841b6
Create Date: 2024-04-15 22:03:59.444626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8243964afff2'
down_revision = '937d05f841b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.drop_column('apply_job')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply_job', postgresql.ENUM('apply_status', name='apply_status'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
