"""new 7.

Revision ID: 937d05f841b6
Revises: 953cc6b40d99
Create Date: 2024-04-15 09:38:55.684343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937d05f841b6'
down_revision = '953cc6b40d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_application', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('last_application')

    # ### end Alembic commands ###
