"""new 6.

Revision ID: 953cc6b40d99
Revises: 709bc244a17b
Create Date: 2024-04-15 09:37:00.420747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953cc6b40d99'
down_revision = '709bc244a17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('Last_application')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Last_application', sa.DATE(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
