"""new 14.

Revision ID: ca1af7dd7044
Revises: b4861c7afdb2
Create Date: 2024-04-22 09:07:55.902152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1af7dd7044'
down_revision = 'b4861c7afdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))

    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))

    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('jobseeker', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
