"""new 9.

Revision ID: ce219dcc9e28
Revises: 8243964afff2
Create Date: 2024-04-15 22:05:04.881724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce219dcc9e28'
down_revision = '8243964afff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply_job', sa.Enum('apply_status', name='apply_status'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.drop_column('apply_job')

    # ### end Alembic commands ###
